// 수자원 IP address
const BASE = 'http://203.253.128.184'
const INGEST_INTERFACE_PORT = '18127'
const DATA_MANAGER_PORT = '18827'
const DATA_SERVICE_BROKER_PORT = '18227'

const INGEST_INTERFACE = BASE+INGEST_INTERFACE_PORT
const DATA_MANAGER = BASE+DATA_MANAGER_PORT
const DATA_SERVICE_BROKER = BASE+DATA_SERVICE_BROKER_PORT

module.exports = {INGEST_INTERFACE, DATA_MANAGER, DATA_SERVICE_BROKER}